remote_theme: chrisrhymes/mere-blog-theme
title: Habla computing Blog
tagline: Purely Functional
url: "https://www.hablapps.com"

paginate: 6
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge


livereload: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Juan Manuel Serrano"
      layout: post
      image: /img/default-post.svg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

collections:
  authors:
    output: true

google_analytics: UA-140060849-1
